# Generated by Django 4.2 on 2025-11-04 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='billetera_cli',
            fields=[
                ('dinero', models.DecimalField(decimal_places=2, max_digits=12)),
                ('idbillcli', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='billetera_tien',
            fields=[
                ('dinero', models.DecimalField(decimal_places=3, max_digits=20)),
                ('idbilltien', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='pro_gallina',
            fields=[
                ('idgallina', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='pro_huevo',
            fields=[
                ('idhuevo', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='venta',
            fields=[
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('idventa', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('idhotel', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('pro_gallina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.pro_gallina')),
            ],
        ),
        migrations.CreateModel(
            name='detalleventa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pro_gallina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.pro_gallina')),
                ('pro_huevo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.pro_huevo')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
            ],
        ),
    ]
