# Generated by Django 4.2 on 2025-11-04 13:17

from django.db import migrations, models
import django.db.models.deletion
import ventas.models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='pro_gallina',
        ),
        migrations.AddField(
            model_name='pro_gallina',
            name='hotel',
            field=models.ForeignKey(default=ventas.models.Hotel_default, on_delete=django.db.models.deletion.CASCADE, to='ventas.hotel'),
        ),
    ]
