# Generated by Django 4.2 on 2025-11-04 13:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_remove_hotel_pro_gallina_pro_gallina_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro_gallina',
            name='check_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pro_gallina',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tipo', models.CharField(choices=[('gallina', 'Gallina'), ('huevo', 'Huevo')], max_length=10)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
            ],
        ),
    ]
