# Generated by Django 4.2 on 2025-11-04 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_pro_gallina_check_in_pro_gallina_check_out_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro_gallina',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='pro_gallina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.pro_gallina'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='pro_huevo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.pro_huevo'),
        ),
    ]
