# Generated by Django 5.2.7 on 2025-11-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_pro_gallina_disponible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pro_gallina',
            name='stock',
        ),
    ]
